name: "Create GitHub release"

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Upstream release
        uses: osbuild/release-action@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
